./" SPDX-FileCopyrightText: 2025 Peter Tribble
./" SPDX-License-Identifier: CDDL-1.0
.TH "JKSTAT" "1" "April 23, 2023"
.SH "NAME"
jkstat \- a java binding to kstat
.SH "SYNOPSIS"
jkstat subcommand [arguments]
.SH DESCRIPTION
The jkstat utility is used to invoke several demonstrations of the
JKstat java bindings to libkstat.
.LP
To see the available subcommands, invoke jkstat without any arguments.
.SH SEE ALSO
kstat(3KSTAT), libkstat(3LIB), kstat(8)
