.TH "JKstat" "1" "Feb 24, 2013" "jkstat 1\&.0"
.SH "NAME"
jkstat \- a java binding to kstat
.SH "SYNOPSIS"
.LP
jkstat subcommand [arguments]
.SH DESCRIPTION
.LP
The jkstat utility is used to invoke several demonstrations of the
JKstat java bindings to libkstat.
.LP
To see the available subcommands, invoke jkstat without any arguments.
.SH SEE ALSO
.LP
kstat(1M), kstat(3KSTAT)
