/*
 * SPDX-License-Identifier: CDDL-1.0
 *
 * CDDL HEADER START
 *
 * This file and its contents are supplied under the terms of the
 * Common Development and Distribution License ("CDDL"), version 1.0.
 * You may only use this file in accordance with the terms of version
 * 1.0 of the CDDL.
 *
 * A full copy of the text of the CDDL should have accompanied this
 * source. A copy of the CDDL is also available via the Internet at
 * http://www.illumos.org/license/CDDL.
 *
 * CDDL HEADER END
 *
 * Copyright 2025 Peter Tribble
 *
 */

package uk.co.petertribble.jkstat.client;

/**
 * An exception class for the JKstat client. This is thrown instead of
 * RunTimeException so that consumers can detect failures, and can identify
 * them as being generated by JKstat rather than being generic java errors.
 *
 * @author Peter Tribble
 */
public class KstatException extends RuntimeException {

    private static final long serialVersionUID = 1L;

    /**
     * Construct a new KstatException.
     */
    public KstatException() {
	super();
    }

    /**
     * Construct a new KstatException with the specified detail message.
     *
     * @param message the detail message
     */
    public KstatException(String message) {
	super(message);
    }

    /**
     * Construct a new KstatException with the specified detail message and
     * cause.
     *
     * @param message the detail message
     * @param cause the underlying cause for this KstatException
     */
    public KstatException(String message, Throwable cause) {
	super(message, cause);
    }
}
