/*
 * SPDX-License-Identifier: CDDL-1.0
 *
 * CDDL HEADER START
 *
 * This file and its contents are supplied under the terms of the
 * Common Development and Distribution License ("CDDL"), version 1.0.
 * You may only use this file in accordance with the terms of version
 * 1.0 of the CDDL.
 *
 * A full copy of the text of the CDDL should have accompanied this
 * source. A copy of the CDDL is also available via the Internet at
 * http://www.illumos.org/license/CDDL.
 *
 * CDDL HEADER END
 *
 * Copyright 2025 Peter Tribble
 *
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class uk_co_petertribble_jkstat_api_NativeJKstat */

#ifndef _Included_uk_co_petertribble_jkstat_api_NativeJKstat
#define _Included_uk_co_petertribble_jkstat_api_NativeJKstat
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     uk_co_petertribble_jkstat_api_NativeJKstat
 * Method:    getKstatObject
 * Signature: (Ljava/lang/String;ILjava/lang/String;)Luk/co/petertribble/jkstat/Kstat;
 */
JNIEXPORT jobject JNICALL Java_uk_co_petertribble_jkstat_api_NativeJKstat_getKstatObject
  (JNIEnv *, jobject, jstring, jint, jstring);

/*
 * Class:     uk_co_petertribble_jkstat_api_NativeJKstat
 * Method:    getKCID
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_uk_co_petertribble_jkstat_api_NativeJKstat_getKCID
  (JNIEnv *, jobject);

/*
 * Class:     uk_co_petertribble_jkstat_api_NativeJKstat
 * Method:    enumerate
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_uk_co_petertribble_jkstat_api_NativeJKstat_enumerate
  (JNIEnv *, jclass);

/*
 * Class:     uk_co_petertribble_jkstat_api_NativeJKstat
 * Method:    cacheids
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_uk_co_petertribble_jkstat_api_NativeJKstat_cacheids
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
