/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class uk_co_petertribble_jkstat_api_NativeJKstat */

#ifndef _Included_uk_co_petertribble_jkstat_api_NativeJKstat
#define _Included_uk_co_petertribble_jkstat_api_NativeJKstat
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     uk_co_petertribble_jkstat_api_NativeJKstat
 * Method:    getKstatObject
 * Signature: (Ljava/lang/String;ILjava/lang/String;)Luk/co/petertribble/jkstat/Kstat;
 */
JNIEXPORT jobject JNICALL Java_uk_co_petertribble_jkstat_api_NativeJKstat_getKstatObject
  (JNIEnv *, jobject, jstring, jint, jstring);

/*
 * Class:     uk_co_petertribble_jkstat_api_NativeJKstat
 * Method:    getKCID
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_uk_co_petertribble_jkstat_api_NativeJKstat_getKCID
  (JNIEnv *, jobject);

/*
 * Class:     uk_co_petertribble_jkstat_api_NativeJKstat
 * Method:    enumerate
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_uk_co_petertribble_jkstat_api_NativeJKstat_enumerate
  (JNIEnv *, jclass);

/*
 * Class:     uk_co_petertribble_jkstat_api_NativeJKstat
 * Method:    cacheids
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_uk_co_petertribble_jkstat_api_NativeJKstat_cacheids
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
